apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.webhook-service" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
  {{- include "operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "operator.labels" . | nindent 4 }}
spec:
  ports:
    {{- if .Values.metricsAuthProxy }}
    - name: https
      port: 8443
      targetPort: https
    {{ else }}
    - name: http
      port: 8080
      targetPort: http
  {{ end }}
  selector:
  {{- include "operator.selectorLabels" . | nindent 4 }}
---